# Настройки глобального логгера
handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler
.level=INFO
# Конфигурация файлового хендлера
java.util.logging.FileHandler.level = ALL
java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter
java.util.logging.FileHandler.count = 0
java.util.logging.FileHandler.limit = 0
java.util.logging.FileHandler.pattern = log%u.txt
java.util.logging.FileHandler.append = true
# Конфигурация консольного хендлера
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter